
//GET USERS
export const REQUEST_GET_USERS         = 'REQUEST_GET_USERS';
export const RECEIVE_GET_USERS_SUCCESS = 'RECEIVE_GET_USERS_SUCCESS';
export const RECEIVE_GET_USERS_ERROR   = 'RECEIVE_GET_USERS_ERROR';

// POST CARDSTEMPLATE
export const REQUEST_ADD_CARDSTEMPLATE         = 'REQUEST_ADD_CARDSTEMPLATE';
export const RECEIVE_ADD_CARDSTEMPLATE_SUCCESS = 'RECEIVE_ADD_CARDSTEMPLATE_SUCCESS';
export const RECEIVE_ADD_CARDSTEMPLATE_ERROR   = 'RECEIVE_ADD_CARDSTEMPLATE_ERROR';

// PUT CARDSTEMPLATE
export const REQUEST_UPDATE_CARDSTEMPLATE         = 'REQUEST_UPDATE_CARDSTEMPLATE';
export const RECEIVE_UPDATE_CARDSTEMPLATE_SUCCESS = 'RECEIVE_UPDATE_CARDSTEMPLATE_SUCCESS';
export const RECEIVE_UPDATE_CARDSTEMPLATE_ERROR   = 'RECEIVE_UPDATE_CARDSTEMPLATE_ERROR';

//GET CARDSTEMPLATES
export const REQUEST_GET_CARDSTEMPLATES         = 'REQUEST_GET_CARDSTEMPLATES';
export const RECEIVE_GET_CARDSTEMPLATES_SUCCESS = 'RECEIVE_GET_CARDSTEMPLATES_SUCCESS';
export const RECEIVE_GET_CARDSTEMPLATES_ERROR   = 'RECEIVE_GET_CARDSTEMPLATES_ERROR';

//FILES
export const SAVE_FILES = 'SAVE_FILES';

//LANGUAGE
export const SAVE_LANGUAGE = 'SAVE_LANGUAGE';